stages:
  - build

build-api:
  stage: build
  only:
    - branches
  except:
    - master
    - develop
  script:
    - 'cd *-api'
    - 'mvn clean deploy -B -e -U -Dmaven.test.skip=true'
  tags:
    - build-jar

build-other-jar:
  stage: build
  only:
    - branches
  except:
    - master
    - develop
  script:
    - 'mvn clean deploy -B -e -U -Dmaven.test.skip=true'
  tags:
    - build-jar
  allow_failure: true
