include: 
  - project: basic/ngari-ci-template
    ref: master
    file: '.ngari-ci-script-template.yml'
variables:
  Type: "api,jar"
  BuildApiOnly: "False"
  BuildApi: "True"
  BuildImage: "True"
  AppName: "ehealth-recipe"
  ApiName: "ehealth-recipe-api"
  PackageName: ""
